// Equal Experts — Panel Roster
// To update: edit this file and re-upload to GitHub.
// The dashboard loads this automatically — your team never needs to upload it manually.

window.PANELS_DATA = [
  { name: "Divya Uppu", type: "Lead" },
  { name: "Aishwarya Agarwal", type: "Lead" },
  { name: "Anay", type: "Lead" },
  { name: "Asif", type: "Lead" },
  { name: "Chintan Shah", type: "Lead" },
  { name: "Hyndavi", type: "Lead" },
  { name: "Kiran Hegde", type: "Lead" },
  { name: "Neeraj Jain", type: "Shadower" },
  { name: "Niranjani", type: "Lead" },
  { name: "Nishant", type: "Lead" },
  { name: "Poorva", type: "Lead" },
  { name: "Pratik Adhau", type: "Lead" },
  { name: "Raghavendra Vaidya", type: "Lead" },
  { name: "Rajesh Pitty", type: "Lead" },
  { name: "Ravi Khakhkhar", type: "Lead" },
  { name: "Shubham Aggarwal", type: "Lead" },
  { name: "Soham Nakhare", type: "Lead" },
  { name: "Srivatsa C", type: "Lead" },
  { name: "Subhajit Saha", type: "Lead" },
  { name: "Sukreet Roy", type: "Lead" },
  { name: "Tabish Shaikh", type: "Lead" },
  { name: "Thameena salahudeen", type: "Lead" },
  { name: "Usama Hamid", type: "Lead" },
  { name: "Vara Prasad", type: "Lead" },
  { name: "Vrushali Waykole", type: "Lead" },
  { name: "Zeeshan Ansari", type: "Lead" },
  { name: "Aasish Singh", type: "Shadower" },
  { name: "Prashant Choudhary", type: "Lead" },
  { name: "Vijayakumar G", type: "Lead" },
  { name: "Peter John", type: "Lead" },
  { name: "Mahesh Bansode", type: "Shadower" },
  { name: "Umar Bashir", type: "Shadower" },
  { name: "Devashish Dhamne", type: "Shadower" },
  { name: "Hiranya Deka", type: "Lead" },
  { name: "Sakthivel Viswanathan", type: "Shadower" },
  { name: "Abhinav Nath", type: "Shadower" },
  { name: "Rahul Bagad", type: "Shadower" },
  { name: "Rahul Chaudhari", type: "Shadower" },
  { name: "Ajay Kumar Singh", type: "Shadower" },
  { name: "Ankur Kumar Singh", type: "Shadower" },
  { name: "Tanveer", type: "Lead" },
  { name: "Divya Murali", type: "Shadower" },
  { name: "Hemanth GS", type: "Lead" },
  { name: "Deepika Misalmani", type: "Shadower" },
  { name: "Vinod U", type: "Shadower" },
  { name: "BalaNagamma", type: "Shadower" },
  { name: "Deepjyoti Borah", type: "Lead" },
  { name: "Soham Chakraborty", type: "Shadower" },
  { name: "Santosh Kamat", type: "Shadower" },
  { name: "Mohd shoaib", type: "Shadower" },
  { name: "Aatish Rana", type: "Shadower" },
  { name: "Saurabh Sharma", type: "Shadower" },
  { name: "Taher Lakdawala", type: "Shadower" },
  { name: "Lalit Kumar Agrawal", type: "Shadower" },
  { name: "Abhishek Bhuskute", type: "Shadower" },
  { name: "Arshadali Sayed", type: "Shadower" },
  { name: "Ashok Chandrashekhar Patrudkar", type: "Shadower" },
  { name: "Ranjit Shinde", type: "Shadower" },
  { name: "Himanshu Agarwal", type: "Lead" },
  { name: "Praveen Raj", type: "Lead" },
  { name: "Sanket Gaikwad", type: "Lead" },
  { name: "Renuga Saraswathy", type: "Lead" },
  { name: "Karthik N", type: "Lead" },
  { name: "Ankit pandey", type: "Lead" },
  { name: "Shantanu Vaidya", type: "Lead" },
  { name: "Aastha", type: "Lead" },
  { name: "Arwa", type: "Lead" },
  { name: "Rohit Phutane", type: "Lead" },
  { name: "Jonathan Bhaskar", type: "Shadower" },
  { name: "Sarvesh Dave", type: "Lead" },
  { name: "Tanmai Naik", type: "Lead" },
  { name: "Tanay", type: "Shadower" },
  { name: "Gobinathan", type: "Shadower" },
  { name: "Anshu Aggarwal", type: "Shadower" },
  { name: "Balu Abraham Kurian", type: "Shadower" },
  { name: "unmesh", type: "Shadower" },
  { name: "Sonu sagar", type: "Shadower" },
  { name: "Karthik Natrajan", type: "Shadower" },
  { name: "Anay Kamat", type: "Lead" },
  { name: "Chetan Gaikwad", type: "Lead" },
  { name: "Gautam Chibde", type: "Lead" },
  { name: "Pradeep Negi", type: "Lead" },
  { name: "Sarang Morde", type: "Shadower" },
  { name: "Vivek Singh", type: "Lead" },
  { name: "Arpit Dongre", type: "Lead" },
  { name: "Karan Gavali", type: "Lead" },
  { name: "Subash Kurapati", type: "Lead" },
  { name: "Prachi Gade", type: "Shadower" },
  { name: "Dinesh Khedkar", type: "Shadower" },
  { name: "Nikhil Pawar", type: "Shadower" },
  { name: "Sonali Kalange", type: "Shadower" },
  { name: "Yogesh Padekar", type: "Shadower" },
  { name: "Rubiya Faniband", type: "Shadower" },
  { name: "Abhishek Goyal", type: "Shadower" },
  { name: "Aditya Mittal", type: "Shadower" },
  { name: "Akhil R Sahdev", type: "Shadower" },
  { name: "Ankur Jain", type: "Shadower" },
  { name: "Anuj Jain", type: "Shadower" },
  { name: "Arunvel Sriram", type: "Shadower" },
  { name: "Ashish Wakchaure", type: "Lead" },
  { name: "Dharani Sowndharya", type: "Shadower" },
  { name: "Dhruvakumar Jonnagaddala", type: "Lead" },
  { name: "Ganesh Prasannah", type: "Lead" },
  { name: "Gaurav Chaudhary", type: "Shadower" },
  { name: "Hamid Raza", type: "Lead" },
  { name: "Jugal Porwal", type: "Shadower" },
  { name: "Mahesh Shekhar", type: "Lead" },
  { name: "Prasanth Gopalakrishnan", type: "Lead" },
  { name: "Pratik bhawsar", type: "Lead" },
  { name: "Ravali Erukulla", type: "Shadower" },
  { name: "Sahil Wadhwa", type: "Lead" },
  { name: "Satish Ingale", type: "Lead" },
  { name: "Shashank Gaur", type: "Lead" },
  { name: "Shiv Ashish", type: "Lead" },
  { name: "Siddhant Agarwal", type: "Lead" },
  { name: "Snehalkumar Mahale", type: "Shadower" },
  { name: "Snigdhajyoti Ghosh", type: "Lead" },
  { name: "Suraj Chavan", type: "Shadower" },
  { name: "Pakeeru", type: "Shadower" },
  { name: "Gaurav Saini", type: "Shadower" },
  { name: "Sriram", type: "Shadower" },
  { name: "Karthik Gupta", type: "Lead" },
  { name: "Ishan Shekar", type: "Lead" },
  { name: "Vishal Desai", type: "Lead" },
  { name: "Abhishek Sharma", type: "Lead" },
  { name: "Rahul Kolekar", type: "Lead" },
  { name: "Ashwini Mayekar", type: "Lead" },
  { name: "Vardhan Bhatt", type: "Lead" },
  { name: "Shalem v", type: "Shadower" },
  { name: "Priyanka Poonacha", type: "Lead" },
  { name: "Smriti Desai", type: "Shadower" },
  { name: "Varun Bansal", type: "Shadower" },
  { name: "Abdul Hafeez", type: "Lead" },
  { name: "Neehar Potdar", type: "Lead" },
  { name: "Shraddha Suman", type: "Shadower" },
  { name: "Mohit Chandna", type: "Shadower" },
  { name: "Munish Malik", type: "Shadower" },
  { name: "Neehar", type: "Lead" },
  { name: "Shrawani", type: "Lead" },
  { name: "Tejaswita", type: "Lead" },
  { name: "Uttam", type: "Lead" },
  { name: "Varun", type: "Lead" },
  { name: "Vishal Desai", type: "Lead" },
  { name: "Vishwas B", type: "Lead" },
  { name: "Ashish", type: "Lead" },
  { name: "Channappa", type: "Shadower" },
  { name: "Anant Pal", type: "Lead" },
  { name: "Karthik Gupta", type: "Shadower" },
  { name: "Ashwini Mayakar", type: "Shadower" },
  { name: "Vishal Sharma", type: "Lead" },
  { name: "Peter John", type: "Lead" },
  { name: "Nitish Kumar", type: "Lead" },
  { name: "Sudeep G", type: "Lead" },
  { name: "Swapnil Pande", type: "Lead" },
  { name: "Aniruddha Ujlambkar", type: "Lead" },
  { name: "Avadhut Prabhdesai", type: "Lead" },
  { name: "Shashank Upadhyay", type: "Lead" },
  { name: "Sahana Ramesh", type: "Lead" },
  { name: "Nidhin T", type: "To be onboarded" },
  { name: "Bergin G", type: "Shadower" },
  { name: "Arindam Sarkar", type: "Shadower" },
  { name: "Nilesh Chaudhari", type: "To be onboarded" },
  { name: "Navid Ansari", type: "To be onboarded" },
  { name: "Amul Jadhav", type: "Shadower" },
  { name: "Aditya Goyal", type: "Shadower" },
  { name: "Priyanshu Shekhar", type: "Lead" },
  { name: "Kapil Koranne", type: "Lead" },
  { name: "Tejeshwar Pradhan", type: "Lead" },
  { name: "Pranjali T", type: "Lead" },
  { name: "Avinash Salimath", type: "Lead" },
  { name: "Anupam Patil", type: "Shadower" },
  { name: "Hansa Asrani", type: "Shadower" },
  { name: "Ayush Jain", type: "Shadower" },
  { name: "Swarnlata Kumari", type: "Shadower" },
  { name: "Lovely", type: "Shadower" },
  { name: "Ananth", type: "Shadower" },
  { name: "Prashant yadav", type: "Shadower" },
  { name: "Purvi Keny", type: "Shadower" },
  { name: "Nagashree", type: "Shadower" },
  { name: "Mohammed Shahid", type: "Shadower" },
  { name: "Mohammed Yusoof", type: "Shadower" },
  { name: "Shraddha", type: "Shadower" },
  { name: "Mohammed Ashiq", type: "Shadower" },
];
